ANNOTATION_BASE = 'http://physiomeproject.org/workflow/1.0/rdf-schema#'

PORT_ANNOTATION = f'{ANNOTATION_BASE}port'

PROVIDES_ANNOTATION = f'{ANNOTATION_BASE}provides'
PROVIDES_LIST_OF_ANNOTATION = f'{ANNOTATION_BASE}provides-list-of'
PROVIDES_ANNOTATIONS = [PROVIDES_ANNOTATION, PROVIDES_LIST_OF_ANNOTATION]

USES_ANNOTATION = f'{ANNOTATION_BASE}uses'
USES_LIST_OF_ANNOTATION = f'{ANNOTATION_BASE}uses-list-of'
USES_ANNOTATIONS = [USES_ANNOTATION, USES_LIST_OF_ANNOTATION]
