
APP_SUCCESS = 0
INVALID_WORKFLOW_LOCATION_GIVEN = 3
HEADLESS_MODE_WITH_NO_WORKFLOW = 5
CONFIGURATION_MODE_WITH_NO_DEFINITIONS = 6
CONFIGURATION_MODE_NO_FILE = 7
LOG_FILE_LOCK_FAILED = 8
USER_SPECIFIED_DIRECTORY = 9
PID_FILE_LOCK_FAILED = 10
CONFIGURATION_MODE_NOT_IMPLEMENTED = 11
