# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'qt/pmrsearchdialog.ui'
#
# Created: Sun Jun 23 20:31:55 2013
#      by: pyside-uic 0.2.14 running on PySide 1.1.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_PMRSearchDialog(object):
    def setupUi(self, PMRSearchDialog):
        PMRSearchDialog.setObjectName("PMRSearchDialog")
        PMRSearchDialog.resize(387, 493)
        self.gridLayout_2 = QtGui.QGridLayout(PMRSearchDialog)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.loginHorizontalLayout = QtGui.QHBoxLayout()
        self.loginHorizontalLayout.setObjectName("loginHorizontalLayout")
        self.label = QtGui.QLabel(PMRSearchDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(10)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName("label")
        self.loginHorizontalLayout.addWidget(self.label)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.loginHorizontalLayout.addItem(spacerItem)
        self.loginStackedWidget = QtGui.QStackedWidget(PMRSearchDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.loginStackedWidget.sizePolicy().hasHeightForWidth())
        self.loginStackedWidget.setSizePolicy(sizePolicy)
        self.loginStackedWidget.setMaximumSize(QtCore.QSize(16777215, 40))
        self.loginStackedWidget.setObjectName("loginStackedWidget")
        self.loginPage = QtGui.QWidget()
        self.loginPage.setObjectName("loginPage")
        self.horizontalLayout = QtGui.QHBoxLayout(self.loginPage)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.registerLabel = QtGui.QLabel(self.loginPage)
        font = QtGui.QFont()
        font.setPointSize(7)
        self.registerLabel.setFont(font)
        self.registerLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.registerLabel.setObjectName("registerLabel")
        self.horizontalLayout.addWidget(self.registerLabel)
        self.loginStackedWidget.addWidget(self.loginPage)
        self.logoutPage = QtGui.QWidget()
        self.logoutPage.setObjectName("logoutPage")
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.logoutPage)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.deregisterLabel = QtGui.QLabel(self.logoutPage)
        font = QtGui.QFont()
        font.setPointSize(7)
        self.deregisterLabel.setFont(font)
        self.deregisterLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.deregisterLabel.setObjectName("deregisterLabel")
        self.horizontalLayout_2.addWidget(self.deregisterLabel)
        self.loginStackedWidget.addWidget(self.logoutPage)
        self.loginHorizontalLayout.addWidget(self.loginStackedWidget)
        self.verticalLayout.addLayout(self.loginHorizontalLayout)
        self.pmrGroupBox = QtGui.QGroupBox(PMRSearchDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.pmrGroupBox.sizePolicy().hasHeightForWidth())
        self.pmrGroupBox.setSizePolicy(sizePolicy)
        self.pmrGroupBox.setTitle("")
        self.pmrGroupBox.setObjectName("pmrGroupBox")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.pmrGroupBox)
        self.verticalLayout_2.setSpacing(5)
        self.verticalLayout_2.setContentsMargins(-1, 0, -1, -1)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.searchLineEdit = QtGui.QLineEdit(self.pmrGroupBox)
        self.searchLineEdit.setObjectName("searchLineEdit")
        self.horizontalLayout_3.addWidget(self.searchLineEdit)
        self.searchButton = QtGui.QPushButton(self.pmrGroupBox)
        self.searchButton.setDefault(True)
        self.searchButton.setObjectName("searchButton")
        self.horizontalLayout_3.addWidget(self.searchButton)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.label_2 = QtGui.QLabel(self.pmrGroupBox)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.searchResultsListWidget = QtGui.QListWidget(self.pmrGroupBox)
        self.searchResultsListWidget.setObjectName("searchResultsListWidget")
        self.verticalLayout_2.addWidget(self.searchResultsListWidget)
        self.verticalLayout.addWidget(self.pmrGroupBox)
        self.buttonBox = QtGui.QDialogButtonBox(PMRSearchDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)
        self.gridLayout_2.addLayout(self.verticalLayout, 0, 0, 1, 1)

        self.retranslateUi(PMRSearchDialog)
        self.loginStackedWidget.setCurrentIndex(0)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("accepted()"), PMRSearchDialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("rejected()"), PMRSearchDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(PMRSearchDialog)
        PMRSearchDialog.setTabOrder(self.searchLineEdit, self.searchButton)
        PMRSearchDialog.setTabOrder(self.searchButton, self.searchResultsListWidget)
        PMRSearchDialog.setTabOrder(self.searchResultsListWidget, self.buttonBox)

    def retranslateUi(self, PMRSearchDialog):
        PMRSearchDialog.setWindowTitle(QtGui.QApplication.translate("PMRSearchDialog", "Physiome Model Repository", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("PMRSearchDialog", "Physiome Model Repository", None, QtGui.QApplication.UnicodeUTF8))
        self.registerLabel.setText(QtGui.QApplication.translate("PMRSearchDialog", "<a href=\"mapclient.register\">register</a>", None, QtGui.QApplication.UnicodeUTF8))
        self.deregisterLabel.setText(QtGui.QApplication.translate("PMRSearchDialog", "<a href=\"http://mapclient.logout\">deregister</a>", None, QtGui.QApplication.UnicodeUTF8))
        self.searchButton.setText(QtGui.QApplication.translate("PMRSearchDialog", "Search", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("PMRSearchDialog", "Search results:", None, QtGui.QApplication.UnicodeUTF8))

