# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'src/mapclient/view/managers/options/qt/optionsdialog.ui',
# licensing of 'src/mapclient/view/managers/options/qt/optionsdialog.ui' applies.
#
# Created: Wed Jun 26 14:33:17 2019
#      by: pyside2-uic  running on PySide2 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_OptionsDialog(object):
    def setupUi(self, OptionsDialog):
        OptionsDialog.setObjectName("OptionsDialog")
        OptionsDialog.resize(525, 579)
        self.gridLayout = QtWidgets.QGridLayout(OptionsDialog)
        self.gridLayout.setObjectName("gridLayout")
        self.buttonBox = QtWidgets.QDialogButtonBox(OptionsDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout.addWidget(self.buttonBox, 2, 0, 1, 1)
        self.tabWidget = QtWidgets.QTabWidget(OptionsDialog)
        self.tabWidget.setObjectName("tabWidget")
        self.tabGeneral = QtWidgets.QWidget()
        self.tabGeneral.setObjectName("tabGeneral")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.tabGeneral)
        self.gridLayout_3.setObjectName("gridLayout_3")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem, 2, 1, 1, 1)
        self.checkBoxShowStepNames = QtWidgets.QCheckBox(self.tabGeneral)
        self.checkBoxShowStepNames.setChecked(True)
        self.checkBoxShowStepNames.setObjectName("checkBoxShowStepNames")
        self.gridLayout_3.addWidget(self.checkBoxShowStepNames, 0, 0, 1, 1)
        self.checkBoxCheckToolsOnStartup = QtWidgets.QCheckBox(self.tabGeneral)
        self.checkBoxCheckToolsOnStartup.setChecked(True)
        self.checkBoxCheckToolsOnStartup.setObjectName("checkBoxCheckToolsOnStartup")
        self.gridLayout_3.addWidget(self.checkBoxCheckToolsOnStartup, 1, 0, 1, 1)
        self.tabWidget.addTab(self.tabGeneral, "")
        self.tabToolSettings = QtWidgets.QWidget()
        self.tabToolSettings.setObjectName("tabToolSettings")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.tabToolSettings)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.groupBox_4 = QtWidgets.QGroupBox(self.tabToolSettings)
        self.groupBox_4.setObjectName("groupBox_4")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox_4)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_2 = QtWidgets.QLabel(self.groupBox_4)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 0, 0, 1, 1)
        self.lineEditPySideRCC = QtWidgets.QLineEdit(self.groupBox_4)
        self.lineEditPySideRCC.setObjectName("lineEditPySideRCC")
        self.gridLayout_2.addWidget(self.lineEditPySideRCC, 0, 1, 1, 1)
        self.pushButtonPySideRCC = QtWidgets.QPushButton(self.groupBox_4)
        self.pushButtonPySideRCC.setObjectName("pushButtonPySideRCC")
        self.gridLayout_2.addWidget(self.pushButtonPySideRCC, 0, 2, 1, 1)
        self.verticalLayout_2.addWidget(self.groupBox_4)
        self.groupBox_5 = QtWidgets.QGroupBox(self.tabToolSettings)
        self.groupBox_5.setObjectName("groupBox_5")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.groupBox_5)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.checkBoxUseExternalGit = QtWidgets.QCheckBox(self.groupBox_5)
        self.checkBoxUseExternalGit.setObjectName("checkBoxUseExternalGit")
        self.verticalLayout_5.addWidget(self.checkBoxUseExternalGit)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.labelGitExecutable = QtWidgets.QLabel(self.groupBox_5)
        self.labelGitExecutable.setObjectName("labelGitExecutable")
        self.horizontalLayout_3.addWidget(self.labelGitExecutable)
        self.lineEditGitExecutable = QtWidgets.QLineEdit(self.groupBox_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEditGitExecutable.sizePolicy().hasHeightForWidth())
        self.lineEditGitExecutable.setSizePolicy(sizePolicy)
        self.lineEditGitExecutable.setObjectName("lineEditGitExecutable")
        self.horizontalLayout_3.addWidget(self.lineEditGitExecutable)
        self.pushButtonGitExecutable = QtWidgets.QPushButton(self.groupBox_5)
        self.pushButtonGitExecutable.setObjectName("pushButtonGitExecutable")
        self.horizontalLayout_3.addWidget(self.pushButtonGitExecutable)
        self.verticalLayout_5.addLayout(self.horizontalLayout_3)
        self.verticalLayout_2.addWidget(self.groupBox_5)
        self.groupBox = QtWidgets.QGroupBox(self.tabToolSettings)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.plainTextEditToolTestOutput = QtWidgets.QPlainTextEdit(self.groupBox)
        self.plainTextEditToolTestOutput.setObjectName("plainTextEditToolTestOutput")
        self.verticalLayout.addWidget(self.plainTextEditToolTestOutput)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.pushButtonRunChecks = QtWidgets.QPushButton(self.groupBox)
        self.pushButtonRunChecks.setObjectName("pushButtonRunChecks")
        self.horizontalLayout.addWidget(self.pushButtonRunChecks)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.verticalLayout_2.addWidget(self.groupBox)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem2)
        self.tabWidget.addTab(self.tabToolSettings, "")
        self.gridLayout.addWidget(self.tabWidget, 0, 0, 1, 1)

        self.retranslateUi(OptionsDialog)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("accepted()"), OptionsDialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("rejected()"), OptionsDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(OptionsDialog)

    def retranslateUi(self, OptionsDialog):
        OptionsDialog.setWindowTitle(QtWidgets.QApplication.translate("OptionsDialog", "Options", None, -1))
        self.checkBoxShowStepNames.setText(QtWidgets.QApplication.translate("OptionsDialog", "Show step names", None, -1))
        self.checkBoxCheckToolsOnStartup.setText(QtWidgets.QApplication.translate("OptionsDialog", "Check tools on application start", None, -1))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabGeneral), QtWidgets.QApplication.translate("OptionsDialog", "&General", None, -1))
        self.groupBox_4.setTitle(QtWidgets.QApplication.translate("OptionsDialog", "Step Wizard", None, -1))
        self.label_2.setText(QtWidgets.QApplication.translate("OptionsDialog", "pyside-rcc", None, -1))
        self.lineEditPySideRCC.setToolTip(QtWidgets.QApplication.translate("OptionsDialog", "The PySide Resource Compiler executable.", None, -1))
        self.pushButtonPySideRCC.setText(QtWidgets.QApplication.translate("OptionsDialog", "...", None, -1))
        self.groupBox_5.setTitle(QtWidgets.QApplication.translate("OptionsDialog", "PMR", None, -1))
        self.checkBoxUseExternalGit.setText(QtWidgets.QApplication.translate("OptionsDialog", "Use external Git", None, -1))
        self.labelGitExecutable.setText(QtWidgets.QApplication.translate("OptionsDialog", "Git:", None, -1))
        self.lineEditGitExecutable.setToolTip(QtWidgets.QApplication.translate("OptionsDialog", "The Git version control executable", None, -1))
        self.pushButtonGitExecutable.setText(QtWidgets.QApplication.translate("OptionsDialog", "...", None, -1))
        self.groupBox.setTitle(QtWidgets.QApplication.translate("OptionsDialog", "Tool test output", None, -1))
        self.pushButtonRunChecks.setText(QtWidgets.QApplication.translate("OptionsDialog", "Run Checks", None, -1))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabToolSettings), QtWidgets.QApplication.translate("OptionsDialog", "Tool Settings", None, -1))

