# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'src/mapclient/tools/annotation/qt/annotationdialog.ui',
# licensing of 'src/mapclient/tools/annotation/qt/annotationdialog.ui' applies.
#
# Created: Wed Jun 26 11:15:11 2019
#      by: pyside2-uic  running on PySide2 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_AnnotationDialog(object):
    def setupUi(self, AnnotationDialog):
        AnnotationDialog.setObjectName("AnnotationDialog")
        AnnotationDialog.resize(462, 560)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(AnnotationDialog)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.groupBox = QtWidgets.QGroupBox(AnnotationDialog)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.locationLineEdit = QtWidgets.QLineEdit(self.groupBox)
        self.locationLineEdit.setEnabled(False)
        self.locationLineEdit.setObjectName("locationLineEdit")
        self.horizontalLayout_2.addWidget(self.locationLineEdit)
        self.gridLayout.addLayout(self.horizontalLayout_2, 0, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.subjectComboBox = QtWidgets.QComboBox(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.subjectComboBox.sizePolicy().hasHeightForWidth())
        self.subjectComboBox.setSizePolicy(sizePolicy)
        self.subjectComboBox.setEditable(True)
        self.subjectComboBox.setObjectName("subjectComboBox")
        self.horizontalLayout.addWidget(self.subjectComboBox)
        self.predicateComboBox = QtWidgets.QComboBox(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.predicateComboBox.sizePolicy().hasHeightForWidth())
        self.predicateComboBox.setSizePolicy(sizePolicy)
        self.predicateComboBox.setEditable(True)
        self.predicateComboBox.setObjectName("predicateComboBox")
        self.horizontalLayout.addWidget(self.predicateComboBox)
        self.objectComboBox = QtWidgets.QComboBox(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.objectComboBox.sizePolicy().hasHeightForWidth())
        self.objectComboBox.setSizePolicy(sizePolicy)
        self.objectComboBox.setEditable(True)
        self.objectComboBox.setObjectName("objectComboBox")
        self.horizontalLayout.addWidget(self.objectComboBox)
        self.gridLayout.addLayout(self.horizontalLayout, 1, 0, 1, 1)
        self.addButton = QtWidgets.QPushButton(self.groupBox)
        self.addButton.setObjectName("addButton")
        self.gridLayout.addWidget(self.addButton, 1, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 2, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setMaximumSize(QtCore.QSize(0, 16777215))
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 1, 1, 1)
        self.annotationListWidget = QtWidgets.QListWidget(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.annotationListWidget.sizePolicy().hasHeightForWidth())
        self.annotationListWidget.setSizePolicy(sizePolicy)
        self.annotationListWidget.setObjectName("annotationListWidget")
        self.gridLayout.addWidget(self.annotationListWidget, 3, 0, 1, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.removeButton = QtWidgets.QPushButton(self.groupBox)
        self.removeButton.setObjectName("removeButton")
        self.verticalLayout.addWidget(self.removeButton)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.gridLayout.addLayout(self.verticalLayout, 3, 1, 1, 1)
        self.fileButton = QtWidgets.QPushButton(self.groupBox)
        self.fileButton.setObjectName("fileButton")
        self.gridLayout.addWidget(self.fileButton, 0, 1, 1, 1)
        self.verticalLayout_2.addWidget(self.groupBox)
        self.buttonBox = QtWidgets.QDialogButtonBox(AnnotationDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout_2.addWidget(self.buttonBox)

        self.retranslateUi(AnnotationDialog)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("rejected()"), AnnotationDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(AnnotationDialog)

    def retranslateUi(self, AnnotationDialog):
        AnnotationDialog.setWindowTitle(QtWidgets.QApplication.translate("AnnotationDialog", "Annotation Tool", None, -1))
        self.groupBox.setTitle(QtWidgets.QApplication.translate("AnnotationDialog", "Annotation Tool", None, -1))
        self.label_2.setText(QtWidgets.QApplication.translate("AnnotationDialog", "Location:", None, -1))
        self.addButton.setText(QtWidgets.QApplication.translate("AnnotationDialog", "Add", None, -1))
        self.label.setText(QtWidgets.QApplication.translate("AnnotationDialog", "Annotations:", None, -1))
        self.label_3.setText(QtWidgets.QApplication.translate("AnnotationDialog", "TextLabel", None, -1))
        self.removeButton.setText(QtWidgets.QApplication.translate("AnnotationDialog", "Remove", None, -1))
        self.fileButton.setText(QtWidgets.QApplication.translate("AnnotationDialog", "...", None, -1))

