# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'qt/configuredialog.ui'
#
# Created: Fri Sep  5 07:45:48 2014
#      by: pyside-uic 0.2.15 running on PySide 1.2.1
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_ConfigureDialog(object):
    def setupUi(self, ConfigureDialog):
        ConfigureDialog.setObjectName("ConfigureDialog")
        ConfigureDialog.resize(629, 581)
        self.verticalLayout_2 = QtGui.QVBoxLayout(ConfigureDialog)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.groupBox = QtGui.QGroupBox(ConfigureDialog)
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout = QtGui.QVBoxLayout(self.groupBox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtGui.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.identifierLineEdit = QtGui.QLineEdit(self.groupBox)
        self.identifierLineEdit.setObjectName("identifierLineEdit")
        self.horizontalLayout.addWidget(self.identifierLineEdit)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.tabWidget = QtGui.QTabWidget(self.groupBox)
        self.tabWidget.setObjectName("tabWidget")
        self.localTab = QtGui.QWidget()
        self.localTab.setObjectName("localTab")
        self.gridLayout = QtGui.QGridLayout(self.localTab)
        self.gridLayout.setObjectName("gridLayout")
        self.label_3 = QtGui.QLabel(self.localTab)
        self.label_3.setMinimumSize(QtCore.QSize(71, 0))
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 0, 0, 1, 1)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 2, 1, 1, 1)
        self.localButton = QtGui.QPushButton(self.localTab)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.localButton.setFont(font)
        self.localButton.setObjectName("localButton")
        self.gridLayout.addWidget(self.localButton, 0, 3, 1, 1)
        self.localLineEdit = QtGui.QLineEdit(self.localTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.localLineEdit.sizePolicy().hasHeightForWidth())
        self.localLineEdit.setSizePolicy(sizePolicy)
        self.localLineEdit.setStyleSheet("selection-color: red;\n"
"color: green")
        self.localLineEdit.setObjectName("localLineEdit")
        self.gridLayout.addWidget(self.localLineEdit, 0, 1, 1, 2)
        self.previousLocationLabel = QtGui.QLabel(self.localTab)
        self.previousLocationLabel.setMaximumSize(QtCore.QSize(0, 16777215))
        self.previousLocationLabel.setText("")
        self.previousLocationLabel.setObjectName("previousLocationLabel")
        self.gridLayout.addWidget(self.previousLocationLabel, 1, 2, 1, 1)
        self.tabWidget.addTab(self.localTab, "")
        self.pmrTab = QtGui.QWidget()
        self.pmrTab.setObjectName("pmrTab")
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.pmrTab)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.tabWidget.addTab(self.pmrTab, "")
        self.verticalLayout.addWidget(self.tabWidget)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_6 = QtGui.QLabel(self.groupBox)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_2.addWidget(self.label_6)
        self.imageSourceTypeComboBox = QtGui.QComboBox(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.imageSourceTypeComboBox.sizePolicy().hasHeightForWidth())
        self.imageSourceTypeComboBox.setSizePolicy(sizePolicy)
        self.imageSourceTypeComboBox.setObjectName("imageSourceTypeComboBox")
        self.imageSourceTypeComboBox.addItem("")
        self.imageSourceTypeComboBox.addItem("")
        self.imageSourceTypeComboBox.addItem("")
        self.imageSourceTypeComboBox.addItem("")
        self.imageSourceTypeComboBox.addItem("")
        self.horizontalLayout_2.addWidget(self.imageSourceTypeComboBox)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.verticalLayout_2.addWidget(self.groupBox)
        self.buttonBox = QtGui.QDialogButtonBox(ConfigureDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout_2.addWidget(self.buttonBox)
        self.label.setBuddy(self.identifierLineEdit)
        self.label_3.setBuddy(self.localLineEdit)
        self.label_6.setBuddy(self.imageSourceTypeComboBox)

        self.retranslateUi(ConfigureDialog)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("accepted()"), ConfigureDialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("rejected()"), ConfigureDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(ConfigureDialog)

    def retranslateUi(self, ConfigureDialog):
        ConfigureDialog.setWindowTitle(QtGui.QApplication.translate("ConfigureDialog", "Configure - Image Source", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("ConfigureDialog", "Identifier:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("ConfigureDialog", "Location:", None, QtGui.QApplication.UnicodeUTF8))
        self.localButton.setText(QtGui.QApplication.translate("ConfigureDialog", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.localTab), QtGui.QApplication.translate("ConfigureDialog", "Local file system", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.pmrTab), QtGui.QApplication.translate("ConfigureDialog", "Physiome Model Repository", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("ConfigureDialog", "Image Source Type:", None, QtGui.QApplication.UnicodeUTF8))
        self.imageSourceTypeComboBox.setItemText(0, QtGui.QApplication.translate("ConfigureDialog", "from file extension", None, QtGui.QApplication.UnicodeUTF8))
        self.imageSourceTypeComboBox.setItemText(1, QtGui.QApplication.translate("ConfigureDialog", "png (*.png)", None, QtGui.QApplication.UnicodeUTF8))
        self.imageSourceTypeComboBox.setItemText(2, QtGui.QApplication.translate("ConfigureDialog", "jpg (*.jpg, *.jpeg)", None, QtGui.QApplication.UnicodeUTF8))
        self.imageSourceTypeComboBox.setItemText(3, QtGui.QApplication.translate("ConfigureDialog", "TIFF (*.tiff)", None, QtGui.QApplication.UnicodeUTF8))
        self.imageSourceTypeComboBox.setItemText(4, QtGui.QApplication.translate("ConfigureDialog", "DICOM (*.dcm)", None, QtGui.QApplication.UnicodeUTF8))

