# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'qt/advanceddialog.ui'
#
# Created: Mon Apr 13 12:12:58 2015
#      by: pyside-uic 0.2.15 running on PySide 1.2.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_AdvancedDialog(object):
    def setupUi(self, AdvancedDialog):
        AdvancedDialog.setObjectName("AdvancedDialog")
        AdvancedDialog.resize(573, 481)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/mapclient/images/icon-app.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        AdvancedDialog.setWindowIcon(icon)
        self.verticalLayout = QtGui.QVBoxLayout(AdvancedDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget = QtGui.QTabWidget(AdvancedDialog)
        self.tabWidget.setTabPosition(QtGui.QTabWidget.North)
        self.tabWidget.setTabShape(QtGui.QTabWidget.Rounded)
        self.tabWidget.setIconSize(QtCore.QSize(16, 16))
        self.tabWidget.setObjectName("tabWidget")
        self.updatesTab = QtGui.QWidget()
        self.updatesTab.setObjectName("updatesTab")
        self.gridLayout_3 = QtGui.QGridLayout(self.updatesTab)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtGui.QLabel(self.updatesTab)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        spacerItem = QtGui.QSpacerItem(218, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.analyseButton = QtGui.QPushButton(self.updatesTab)
        self.analyseButton.setMinimumSize(QtCore.QSize(100, 0))
        self.analyseButton.setWhatsThis("")
        self.analyseButton.setObjectName("analyseButton")
        self.horizontalLayout.addWidget(self.analyseButton)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.listWidget = QtGui.QListWidget(self.updatesTab)
        self.listWidget.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.listWidget.setSelectionMode(QtGui.QAbstractItemView.ExtendedSelection)
        self.listWidget.setObjectName("listWidget")
        self.verticalLayout_2.addWidget(self.listWidget)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtGui.QLabel(self.updatesTab)
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        spacerItem1 = QtGui.QSpacerItem(118, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.updateAllButton = QtGui.QPushButton(self.updatesTab)
        self.updateAllButton.setObjectName("updateAllButton")
        self.horizontalLayout_2.addWidget(self.updateAllButton)
        self.updateButton = QtGui.QPushButton(self.updatesTab)
        self.updateButton.setObjectName("updateButton")
        self.horizontalLayout_2.addWidget(self.updateButton)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.gridLayout_3.addLayout(self.verticalLayout_2, 0, 0, 1, 1)
        self.tabWidget.addTab(self.updatesTab, "")
        self.dependenciesTab = QtGui.QWidget()
        self.dependenciesTab.setObjectName("dependenciesTab")
        self.gridLayout_4 = QtGui.QGridLayout(self.dependenciesTab)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.verticalLayout_10 = QtGui.QVBoxLayout()
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.verticalLayout_5 = QtGui.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_8 = QtGui.QLabel(self.dependenciesTab)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_5.addWidget(self.label_8)
        self.installedPackagesList = QtGui.QListWidget(self.dependenciesTab)
        self.installedPackagesList.setObjectName("installedPackagesList")
        self.verticalLayout_5.addWidget(self.installedPackagesList)
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.failedInstallsButton = QtGui.QPushButton(self.dependenciesTab)
        self.failedInstallsButton.setMinimumSize(QtCore.QSize(90, 0))
        self.failedInstallsButton.setObjectName("failedInstallsButton")
        self.horizontalLayout_9.addWidget(self.failedInstallsButton)
        self.updatePackages = QtGui.QPushButton(self.dependenciesTab)
        self.updatePackages.setObjectName("updatePackages")
        self.horizontalLayout_9.addWidget(self.updatePackages)
        self.uninstallPackages = QtGui.QPushButton(self.dependenciesTab)
        self.uninstallPackages.setObjectName("uninstallPackages")
        self.horizontalLayout_9.addWidget(self.uninstallPackages)
        self.verticalLayout_5.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_8.addLayout(self.verticalLayout_5)
        self.verticalLayout_11 = QtGui.QVBoxLayout()
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.label_9 = QtGui.QLabel(self.dependenciesTab)
        self.label_9.setObjectName("label_9")
        self.verticalLayout_11.addWidget(self.label_9)
        self.recommendedPackagesList = QtGui.QListWidget(self.dependenciesTab)
        self.recommendedPackagesList.setObjectName("recommendedPackagesList")
        self.verticalLayout_11.addWidget(self.recommendedPackagesList)
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem2)
        self.installPackages = QtGui.QPushButton(self.dependenciesTab)
        self.installPackages.setObjectName("installPackages")
        self.horizontalLayout_10.addWidget(self.installPackages)
        self.packageInformation = QtGui.QPushButton(self.dependenciesTab)
        self.packageInformation.setObjectName("packageInformation")
        self.horizontalLayout_10.addWidget(self.packageInformation)
        self.verticalLayout_11.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_8.addLayout(self.verticalLayout_11)
        self.verticalLayout_10.addLayout(self.horizontalLayout_8)
        self.groupBox_2 = QtGui.QGroupBox(self.dependenciesTab)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_2 = QtGui.QGridLayout(self.groupBox_2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.horizontalLayout_11 = QtGui.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.defaultVELocationCheckBox = QtGui.QCheckBox(self.groupBox_2)
        self.defaultVELocationCheckBox.setObjectName("defaultVELocationCheckBox")
        self.horizontalLayout_11.addWidget(self.defaultVELocationCheckBox)
        self.virtualenvCheckBox = QtGui.QCheckBox(self.groupBox_2)
        self.virtualenvCheckBox.setObjectName("virtualenvCheckBox")
        self.horizontalLayout_11.addWidget(self.virtualenvCheckBox)
        self.syntaxUpdatesCheckBox = QtGui.QCheckBox(self.groupBox_2)
        self.syntaxUpdatesCheckBox.setObjectName("syntaxUpdatesCheckBox")
        self.horizontalLayout_11.addWidget(self.syntaxUpdatesCheckBox)
        self.gridLayout_2.addLayout(self.horizontalLayout_11, 0, 0, 1, 1)
        self.verticalLayout_10.addWidget(self.groupBox_2)
        self.verticalLayout_12 = QtGui.QVBoxLayout()
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.label_7 = QtGui.QLabel(self.dependenciesTab)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_12.addWidget(self.label_7)
        self.horizontalLayout_12 = QtGui.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.virtEnvLocation = QtGui.QLineEdit(self.dependenciesTab)
        self.virtEnvLocation.setObjectName("virtEnvLocation")
        self.horizontalLayout_12.addWidget(self.virtEnvLocation)
        self.modifyVELocation = QtGui.QPushButton(self.dependenciesTab)
        self.modifyVELocation.setObjectName("modifyVELocation")
        self.horizontalLayout_12.addWidget(self.modifyVELocation)
        self.verticalLayout_12.addLayout(self.horizontalLayout_12)
        self.verticalLayout_10.addLayout(self.verticalLayout_12)
        self.gridLayout_4.addLayout(self.verticalLayout_10, 0, 0, 1, 1)
        self.tabWidget.addTab(self.dependenciesTab, "")
        self.optionsTab = QtGui.QWidget()
        self.optionsTab.setObjectName("optionsTab")
        self.verticalLayout_9 = QtGui.QVBoxLayout(self.optionsTab)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.groupBox = QtGui.QGroupBox(self.optionsTab)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtGui.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_3 = QtGui.QLabel(self.groupBox)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_4.addWidget(self.label_3)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem3)
        self.revertButton = QtGui.QPushButton(self.groupBox)
        self.revertButton.setCheckable(False)
        self.revertButton.setFlat(False)
        self.revertButton.setObjectName("revertButton")
        self.horizontalLayout_4.addWidget(self.revertButton)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        self.ignoreList = QtGui.QListWidget(self.groupBox)
        self.ignoreList.setSelectionMode(QtGui.QAbstractItemView.ExtendedSelection)
        self.ignoreList.setObjectName("ignoreList")
        self.verticalLayout_3.addWidget(self.ignoreList)
        self.gridLayout.addLayout(self.verticalLayout_3, 0, 0, 1, 1)
        self.showPluginErrors = QtGui.QCheckBox(self.groupBox)
        self.showPluginErrors.setChecked(True)
        self.showPluginErrors.setObjectName("showPluginErrors")
        self.gridLayout.addWidget(self.showPluginErrors, 1, 0, 1, 1)
        self.horizontalLayout_7.addWidget(self.groupBox)
        self.groupBox1 = QtGui.QGroupBox(self.optionsTab)
        self.groupBox1.setObjectName("groupBox1")
        self.verticalLayout_8 = QtGui.QVBoxLayout(self.groupBox1)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.verticalLayout_7 = QtGui.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.syntaxCheckBox = QtGui.QCheckBox(self.groupBox1)
        self.syntaxCheckBox.setChecked(True)
        self.syntaxCheckBox.setObjectName("syntaxCheckBox")
        self.verticalLayout_7.addWidget(self.syntaxCheckBox)
        self.indentCheckBox = QtGui.QCheckBox(self.groupBox1)
        self.indentCheckBox.setChecked(True)
        self.indentCheckBox.setObjectName("indentCheckBox")
        self.verticalLayout_7.addWidget(self.indentCheckBox)
        self.resourceCheckBox = QtGui.QCheckBox(self.groupBox1)
        self.resourceCheckBox.setChecked(True)
        self.resourceCheckBox.setObjectName("resourceCheckBox")
        self.verticalLayout_7.addWidget(self.resourceCheckBox)
        self.locationCheckBox = QtGui.QCheckBox(self.groupBox1)
        self.locationCheckBox.setChecked(True)
        self.locationCheckBox.setObjectName("locationCheckBox")
        self.verticalLayout_7.addWidget(self.locationCheckBox)
        self.verticalLayout_8.addLayout(self.verticalLayout_7)
        self.verticalLayout_6 = QtGui.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_5 = QtGui.QLabel(self.groupBox1)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_6.addWidget(self.label_5)
        self.resourceList = QtGui.QListWidget(self.groupBox1)
        self.resourceList.setSelectionMode(QtGui.QAbstractItemView.ExtendedSelection)
        self.resourceList.setObjectName("resourceList")
        self.verticalLayout_6.addWidget(self.resourceList)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.lineEdit = QtGui.QLineEdit(self.groupBox1)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout_6.addWidget(self.lineEdit)
        self.addResource = QtGui.QPushButton(self.groupBox1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.addResource.sizePolicy().hasHeightForWidth())
        self.addResource.setSizePolicy(sizePolicy)
        self.addResource.setMinimumSize(QtCore.QSize(0, 0))
        self.addResource.setMaximumSize(QtCore.QSize(30, 23))
        self.addResource.setObjectName("addResource")
        self.horizontalLayout_6.addWidget(self.addResource)
        self.removeResource = QtGui.QPushButton(self.groupBox1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.removeResource.sizePolicy().hasHeightForWidth())
        self.removeResource.setSizePolicy(sizePolicy)
        self.removeResource.setMinimumSize(QtCore.QSize(0, 0))
        self.removeResource.setMaximumSize(QtCore.QSize(30, 23))
        self.removeResource.setObjectName("removeResource")
        self.horizontalLayout_6.addWidget(self.removeResource)
        self.verticalLayout_6.addLayout(self.horizontalLayout_6)
        self.verticalLayout_8.addLayout(self.verticalLayout_6)
        self.horizontalLayout_7.addWidget(self.groupBox1)
        self.verticalLayout_9.addLayout(self.horizontalLayout_7)
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_4 = QtGui.QLabel(self.optionsTab)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_4.addWidget(self.label_4)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.dir2to3 = QtGui.QLineEdit(self.optionsTab)
        self.dir2to3.setObjectName("dir2to3")
        self.horizontalLayout_5.addWidget(self.dir2to3)
        self.locateButton = QtGui.QPushButton(self.optionsTab)
        self.locateButton.setObjectName("locateButton")
        self.horizontalLayout_5.addWidget(self.locateButton)
        self.verticalLayout_4.addLayout(self.horizontalLayout_5)
        self.verticalLayout_9.addLayout(self.verticalLayout_4)
        self.tabWidget.addTab(self.optionsTab, "")
        self.verticalLayout.addWidget(self.tabWidget)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.buttonBox = QtGui.QDialogButtonBox(AdvancedDialog)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel | QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.horizontalLayout_3.addWidget(self.buttonBox)
        self.verticalLayout.addLayout(self.horizontalLayout_3)

        self.retranslateUi(AdvancedDialog)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("accepted()"), AdvancedDialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("rejected()"), AdvancedDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(AdvancedDialog)

    def retranslateUi(self, AdvancedDialog):
        AdvancedDialog.setWindowTitle(QtGui.QApplication.translate("AdvancedDialog", "Advanced", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("AdvancedDialog", "Plugins:", None, QtGui.QApplication.UnicodeUTF8))
        self.analyseButton.setText(QtGui.QApplication.translate("AdvancedDialog", "Analyse Plugins", None, QtGui.QApplication.UnicodeUTF8))
        self.updateAllButton.setText(QtGui.QApplication.translate("AdvancedDialog", "Update All", None, QtGui.QApplication.UnicodeUTF8))
        self.updateButton.setText(QtGui.QApplication.translate("AdvancedDialog", "Update", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.updatesTab), QtGui.QApplication.translate("AdvancedDialog", "Updates", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("AdvancedDialog", "Installed Packages:", None, QtGui.QApplication.UnicodeUTF8))
        self.failedInstallsButton.setText(QtGui.QApplication.translate("AdvancedDialog", "Failed Installs...", None, QtGui.QApplication.UnicodeUTF8))
        self.updatePackages.setText(QtGui.QApplication.translate("AdvancedDialog", "Update", None, QtGui.QApplication.UnicodeUTF8))
        self.uninstallPackages.setText(QtGui.QApplication.translate("AdvancedDialog", "Uninstall", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("AdvancedDialog", "Recommended Packages:", None, QtGui.QApplication.UnicodeUTF8))
        self.installPackages.setText(QtGui.QApplication.translate("AdvancedDialog", "Install", None, QtGui.QApplication.UnicodeUTF8))
        self.packageInformation.setText(QtGui.QApplication.translate("AdvancedDialog", "Information", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("AdvancedDialog", "Dependency Settings", None, QtGui.QApplication.UnicodeUTF8))
        self.defaultVELocationCheckBox.setText(QtGui.QApplication.translate("AdvancedDialog", "Automatically check for updates", None, QtGui.QApplication.UnicodeUTF8))
        self.virtualenvCheckBox.setText(QtGui.QApplication.translate("AdvancedDialog", "Double-click for documentation", None, QtGui.QApplication.UnicodeUTF8))
        self.syntaxUpdatesCheckBox.setText(QtGui.QApplication.translate("AdvancedDialog", "Check for syntax updates", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("AdvancedDialog", "Virtual Environment Location:", None, QtGui.QApplication.UnicodeUTF8))
        self.modifyVELocation.setText(QtGui.QApplication.translate("AdvancedDialog", "Modify", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.dependenciesTab), QtGui.QApplication.translate("AdvancedDialog", "Dependencies", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("AdvancedDialog", "Plugin Error Settings", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("AdvancedDialog", "Ignored Plugins:", None, QtGui.QApplication.UnicodeUTF8))
        self.revertButton.setText(QtGui.QApplication.translate("AdvancedDialog", "Revert", None, QtGui.QApplication.UnicodeUTF8))
        self.showPluginErrors.setText(QtGui.QApplication.translate("AdvancedDialog", "Show Plugin Errors Dialog", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox1.setTitle(QtGui.QApplication.translate("AdvancedDialog", "Plugin Updater Settings", None, QtGui.QApplication.UnicodeUTF8))
        self.syntaxCheckBox.setText(QtGui.QApplication.translate("AdvancedDialog", "Syntax updates", None, QtGui.QApplication.UnicodeUTF8))
        self.indentCheckBox.setText(QtGui.QApplication.translate("AdvancedDialog", "Indentation updates", None, QtGui.QApplication.UnicodeUTF8))
        self.resourceCheckBox.setText(QtGui.QApplication.translate("AdvancedDialog", "Resource updates", None, QtGui.QApplication.UnicodeUTF8))
        self.locationCheckBox.setText(QtGui.QApplication.translate("AdvancedDialog", "Location updates", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("AdvancedDialog", "Resource Filenames:", None, QtGui.QApplication.UnicodeUTF8))
        self.addResource.setText(QtGui.QApplication.translate("AdvancedDialog", "+", None, QtGui.QApplication.UnicodeUTF8))
        self.removeResource.setText(QtGui.QApplication.translate("AdvancedDialog", "-", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("AdvancedDialog", "2to3.py Location:", None, QtGui.QApplication.UnicodeUTF8))
        self.locateButton.setText(QtGui.QApplication.translate("AdvancedDialog", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.optionsTab), QtGui.QApplication.translate("AdvancedDialog", "Options", None, QtGui.QApplication.UnicodeUTF8))

