# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'qt\renamedialog.ui'
#
# Created: Wed Aug 10 15:06:02 2016
#      by: pyside-uic 0.2.15 running on PySide 1.2.4
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_RenameDialog(object):
    def setupUi(self, RenameDialog):
        RenameDialog.setObjectName("RenameDialog")
        RenameDialog.resize(491, 357)
        self.verticalLayout = QtGui.QVBoxLayout(RenameDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox = QtGui.QGroupBox(RenameDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(2)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.groupBox)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_4 = QtGui.QLabel(self.groupBox)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_2.addWidget(self.label_4)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lineEditStepLocation = QtGui.QLineEdit(self.groupBox)
        self.lineEditStepLocation.setObjectName("lineEditStepLocation")
        self.horizontalLayout.addWidget(self.lineEditStepLocation)
        self.pushButtonStepChooser = QtGui.QPushButton(self.groupBox)
        self.pushButtonStepChooser.setObjectName("pushButtonStepChooser")
        self.horizontalLayout.addWidget(self.pushButtonStepChooser)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label_9 = QtGui.QLabel(self.groupBox)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 1, 2, 1, 1)
        self.lineEditRenamePackageFrom = QtGui.QLineEdit(self.groupBox)
        self.lineEditRenamePackageFrom.setEnabled(False)
        self.lineEditRenamePackageFrom.setReadOnly(True)
        self.lineEditRenamePackageFrom.setObjectName("lineEditRenamePackageFrom")
        self.gridLayout.addWidget(self.lineEditRenamePackageFrom, 1, 1, 1, 1)
        self.lineEditRenamePackageTo = QtGui.QLineEdit(self.groupBox)
        self.lineEditRenamePackageTo.setObjectName("lineEditRenamePackageTo")
        self.gridLayout.addWidget(self.lineEditRenamePackageTo, 1, 3, 1, 1)
        self.label_10 = QtGui.QLabel(self.groupBox)
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 1, 0, 1, 1)
        self.label = QtGui.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.label_3 = QtGui.QLabel(self.groupBox)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 0, 2, 1, 1)
        self.lineEditRenameStepTo = QtGui.QLineEdit(self.groupBox)
        self.lineEditRenameStepTo.setObjectName("lineEditRenameStepTo")
        self.gridLayout.addWidget(self.lineEditRenameStepTo, 0, 3, 1, 1)
        self.lineEditRenameStepFrom = QtGui.QLineEdit(self.groupBox)
        self.lineEditRenameStepFrom.setEnabled(False)
        self.lineEditRenameStepFrom.setReadOnly(True)
        self.lineEditRenameStepFrom.setObjectName("lineEditRenameStepFrom")
        self.gridLayout.addWidget(self.lineEditRenameStepFrom, 0, 1, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout)
        self.treeWidgetRename = QtGui.QTreeWidget(self.groupBox)
        self.treeWidgetRename.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.treeWidgetRename.setObjectName("treeWidgetRename")
        self.treeWidgetRename.headerItem().setText(0, "1")
        self.treeWidgetRename.header().setVisible(False)
        self.verticalLayout_2.addWidget(self.treeWidgetRename)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.verticalLayout.addWidget(self.groupBox)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButtonRename = QtGui.QPushButton(RenameDialog)
        self.pushButtonRename.setObjectName("pushButtonRename")
        self.horizontalLayout_2.addWidget(self.pushButtonRename)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.pushButtonCancel = QtGui.QPushButton(RenameDialog)
        self.pushButtonCancel.setObjectName("pushButtonCancel")
        self.horizontalLayout_2.addWidget(self.pushButtonCancel)
        self.verticalLayout.addLayout(self.horizontalLayout_2)

        self.retranslateUi(RenameDialog)
        QtCore.QObject.connect(self.pushButtonCancel, QtCore.SIGNAL("clicked()"), RenameDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(RenameDialog)
        RenameDialog.setTabOrder(self.lineEditStepLocation, self.pushButtonStepChooser)
        RenameDialog.setTabOrder(self.pushButtonStepChooser, self.lineEditRenameStepTo)
        RenameDialog.setTabOrder(self.lineEditRenameStepTo, self.lineEditRenamePackageTo)
        RenameDialog.setTabOrder(self.lineEditRenamePackageTo, self.treeWidgetRename)
        RenameDialog.setTabOrder(self.treeWidgetRename, self.pushButtonRename)
        RenameDialog.setTabOrder(self.pushButtonRename, self.pushButtonCancel)
        RenameDialog.setTabOrder(self.pushButtonCancel, self.lineEditRenameStepFrom)
        RenameDialog.setTabOrder(self.lineEditRenameStepFrom, self.lineEditRenamePackageFrom)

    def retranslateUi(self, RenameDialog):
        RenameDialog.setWindowTitle(QtGui.QApplication.translate("RenameDialog", "Rename Step Tool", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("RenameDialog", "Step to rename (location on disk):", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonStepChooser.setText(QtGui.QApplication.translate("RenameDialog", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("RenameDialog", " to:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("RenameDialog", "Rename Package name from:", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("RenameDialog", "Rename Step name from:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("RenameDialog", " to:", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonRename.setText(QtGui.QApplication.translate("RenameDialog", "Rename", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonCancel.setText(QtGui.QApplication.translate("RenameDialog", "Cancel", None, QtGui.QApplication.UnicodeUTF8))

