# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'qt/advanceddialog.ui'
#
# Created: Thu Jan 29 14:10:42 2015
#      by: pyside-uic 0.2.15 running on PySide 1.2.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_AdvancedDialog(object):
    def setupUi(self, AdvancedDialog):
        AdvancedDialog.setObjectName("AdvancedDialog")
        AdvancedDialog.resize(525, 450)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/mapclient/images/icon-app.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        AdvancedDialog.setWindowIcon(icon)
        self.verticalLayout = QtGui.QVBoxLayout(AdvancedDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget = QtGui.QTabWidget(AdvancedDialog)
        self.tabWidget.setTabPosition(QtGui.QTabWidget.North)
        self.tabWidget.setTabShape(QtGui.QTabWidget.Rounded)
        self.tabWidget.setIconSize(QtCore.QSize(16, 16))
        self.tabWidget.setObjectName("tabWidget")
        self.updatesTab = QtGui.QWidget()
        self.updatesTab.setObjectName("updatesTab")
        self.gridLayout_3 = QtGui.QGridLayout(self.updatesTab)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtGui.QLabel(self.updatesTab)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        spacerItem = QtGui.QSpacerItem(218, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.analyseButton = QtGui.QPushButton(self.updatesTab)
        self.analyseButton.setMinimumSize(QtCore.QSize(100, 0))
        self.analyseButton.setObjectName("analyseButton")
        self.horizontalLayout.addWidget(self.analyseButton)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.listWidget = QtGui.QListWidget(self.updatesTab)
        self.listWidget.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.listWidget.setSelectionMode(QtGui.QAbstractItemView.ExtendedSelection)
        self.listWidget.setObjectName("listWidget")
        self.verticalLayout_2.addWidget(self.listWidget)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtGui.QLabel(self.updatesTab)
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        spacerItem1 = QtGui.QSpacerItem(118, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.updateAllButton = QtGui.QPushButton(self.updatesTab)
        self.updateAllButton.setObjectName("updateAllButton")
        self.horizontalLayout_2.addWidget(self.updateAllButton)
        self.updateButton = QtGui.QPushButton(self.updatesTab)
        self.updateButton.setObjectName("updateButton")
        self.horizontalLayout_2.addWidget(self.updateButton)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.gridLayout_3.addLayout(self.verticalLayout_2, 0, 0, 1, 1)
        self.tabWidget.addTab(self.updatesTab, "")
        self.optionsTab = QtGui.QWidget()
        self.optionsTab.setObjectName("optionsTab")
        self.gridLayout_2 = QtGui.QGridLayout(self.optionsTab)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.groupBox = QtGui.QGroupBox(self.optionsTab)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtGui.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_3 = QtGui.QLabel(self.groupBox)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_4.addWidget(self.label_3)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem2)
        self.revertButton = QtGui.QPushButton(self.groupBox)
        self.revertButton.setCheckable(False)
        self.revertButton.setFlat(False)
        self.revertButton.setObjectName("revertButton")
        self.horizontalLayout_4.addWidget(self.revertButton)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        self.ignoreList = QtGui.QListWidget(self.groupBox)
        self.ignoreList.setSelectionMode(QtGui.QAbstractItemView.ExtendedSelection)
        self.ignoreList.setObjectName("ignoreList")
        self.verticalLayout_3.addWidget(self.ignoreList)
        self.gridLayout.addLayout(self.verticalLayout_3, 0, 0, 1, 1)
        self.showPluginErrors = QtGui.QCheckBox(self.groupBox)
        self.showPluginErrors.setChecked(True)
        self.showPluginErrors.setObjectName("showPluginErrors")
        self.gridLayout.addWidget(self.showPluginErrors, 1, 0, 1, 1)
        self.horizontalLayout_7.addWidget(self.groupBox)
        self.groupBox1 = QtGui.QGroupBox(self.optionsTab)
        self.groupBox1.setObjectName("groupBox1")
        self.verticalLayout_8 = QtGui.QVBoxLayout(self.groupBox1)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.verticalLayout_7 = QtGui.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.syntaxCheckBox = QtGui.QCheckBox(self.groupBox1)
        self.syntaxCheckBox.setChecked(True)
        self.syntaxCheckBox.setObjectName("syntaxCheckBox")
        self.verticalLayout_7.addWidget(self.syntaxCheckBox)
        self.indentCheckBox = QtGui.QCheckBox(self.groupBox1)
        self.indentCheckBox.setChecked(True)
        self.indentCheckBox.setObjectName("indentCheckBox")
        self.verticalLayout_7.addWidget(self.indentCheckBox)
        self.resourceCheckBox = QtGui.QCheckBox(self.groupBox1)
        self.resourceCheckBox.setChecked(True)
        self.resourceCheckBox.setObjectName("resourceCheckBox")
        self.verticalLayout_7.addWidget(self.resourceCheckBox)
        self.locationCheckBox = QtGui.QCheckBox(self.groupBox1)
        self.locationCheckBox.setChecked(True)
        self.locationCheckBox.setObjectName("locationCheckBox")
        self.verticalLayout_7.addWidget(self.locationCheckBox)
        self.dependencyUpdates = QtGui.QCheckBox(self.groupBox1)
        self.dependencyUpdates.setChecked(False)
        self.dependencyUpdates.setObjectName("dependencyUpdates")
        self.verticalLayout_7.addWidget(self.dependencyUpdates)
        self.verticalLayout_8.addLayout(self.verticalLayout_7)
        self.verticalLayout_6 = QtGui.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_5 = QtGui.QLabel(self.groupBox1)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_6.addWidget(self.label_5)
        self.resourceList = QtGui.QListWidget(self.groupBox1)
        self.resourceList.setSelectionMode(QtGui.QAbstractItemView.ExtendedSelection)
        self.resourceList.setObjectName("resourceList")
        self.verticalLayout_6.addWidget(self.resourceList)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.lineEdit = QtGui.QLineEdit(self.groupBox1)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout_6.addWidget(self.lineEdit)
        self.addResource = QtGui.QPushButton(self.groupBox1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.addResource.sizePolicy().hasHeightForWidth())
        self.addResource.setSizePolicy(sizePolicy)
        self.addResource.setMinimumSize(QtCore.QSize(0, 0))
        self.addResource.setMaximumSize(QtCore.QSize(30, 23))
        self.addResource.setObjectName("addResource")
        self.horizontalLayout_6.addWidget(self.addResource)
        self.removeResource = QtGui.QPushButton(self.groupBox1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.removeResource.sizePolicy().hasHeightForWidth())
        self.removeResource.setSizePolicy(sizePolicy)
        self.removeResource.setMinimumSize(QtCore.QSize(0, 0))
        self.removeResource.setMaximumSize(QtCore.QSize(30, 23))
        self.removeResource.setObjectName("removeResource")
        self.horizontalLayout_6.addWidget(self.removeResource)
        self.verticalLayout_6.addLayout(self.horizontalLayout_6)
        self.verticalLayout_8.addLayout(self.verticalLayout_6)
        self.horizontalLayout_7.addWidget(self.groupBox1)
        self.gridLayout_2.addLayout(self.horizontalLayout_7, 0, 0, 1, 1)
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_4 = QtGui.QLabel(self.optionsTab)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_4.addWidget(self.label_4)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.dir2to3 = QtGui.QLineEdit(self.optionsTab)
        self.dir2to3.setObjectName("dir2to3")
        self.horizontalLayout_5.addWidget(self.dir2to3)
        self.locateButton = QtGui.QPushButton(self.optionsTab)
        self.locateButton.setObjectName("locateButton")
        self.horizontalLayout_5.addWidget(self.locateButton)
        self.verticalLayout_4.addLayout(self.horizontalLayout_5)
        self.gridLayout_2.addLayout(self.verticalLayout_4, 1, 0, 1, 1)
        self.tabWidget.addTab(self.optionsTab, "")
        self.verticalLayout.addWidget(self.tabWidget)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.buttonBox = QtGui.QDialogButtonBox(AdvancedDialog)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.horizontalLayout_3.addWidget(self.buttonBox)
        self.verticalLayout.addLayout(self.horizontalLayout_3)

        self.retranslateUi(AdvancedDialog)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("accepted()"), AdvancedDialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("rejected()"), AdvancedDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(AdvancedDialog)

    def retranslateUi(self, AdvancedDialog):
        AdvancedDialog.setWindowTitle(QtGui.QApplication.translate("AdvancedDialog", "Advanced", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("AdvancedDialog", "Plugins:", None, QtGui.QApplication.UnicodeUTF8))
        self.analyseButton.setText(QtGui.QApplication.translate("AdvancedDialog", "Analyse Plugins", None, QtGui.QApplication.UnicodeUTF8))
        self.updateAllButton.setText(QtGui.QApplication.translate("AdvancedDialog", "Update All", None, QtGui.QApplication.UnicodeUTF8))
        self.updateButton.setText(QtGui.QApplication.translate("AdvancedDialog", "Update", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.updatesTab), QtGui.QApplication.translate("AdvancedDialog", "Updates", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("AdvancedDialog", "Plugin Error Settings", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("AdvancedDialog", "Ignored Plugins:", None, QtGui.QApplication.UnicodeUTF8))
        self.revertButton.setText(QtGui.QApplication.translate("AdvancedDialog", "Revert", None, QtGui.QApplication.UnicodeUTF8))
        self.showPluginErrors.setText(QtGui.QApplication.translate("AdvancedDialog", "Show Plugin Errors Dialog", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox1.setTitle(QtGui.QApplication.translate("AdvancedDialog", "Plugin Updater Settings", None, QtGui.QApplication.UnicodeUTF8))
        self.syntaxCheckBox.setText(QtGui.QApplication.translate("AdvancedDialog", "Syntax updates", None, QtGui.QApplication.UnicodeUTF8))
        self.indentCheckBox.setText(QtGui.QApplication.translate("AdvancedDialog", "Indentation updates", None, QtGui.QApplication.UnicodeUTF8))
        self.resourceCheckBox.setText(QtGui.QApplication.translate("AdvancedDialog", "Resource updates", None, QtGui.QApplication.UnicodeUTF8))
        self.locationCheckBox.setText(QtGui.QApplication.translate("AdvancedDialog", "Location updates", None, QtGui.QApplication.UnicodeUTF8))
        self.dependencyUpdates.setText(QtGui.QApplication.translate("AdvancedDialog", "Include dependency updates", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("AdvancedDialog", "Resource Filenames:", None, QtGui.QApplication.UnicodeUTF8))
        self.addResource.setText(QtGui.QApplication.translate("AdvancedDialog", "+", None, QtGui.QApplication.UnicodeUTF8))
        self.removeResource.setText(QtGui.QApplication.translate("AdvancedDialog", "-", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("AdvancedDialog", "2to3.py Location:", None, QtGui.QApplication.UnicodeUTF8))
        self.locateButton.setText(QtGui.QApplication.translate("AdvancedDialog", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.optionsTab), QtGui.QApplication.translate("AdvancedDialog", "Options", None, QtGui.QApplication.UnicodeUTF8))

from . import resources_rc
