name: test-win-signing

on:
  push

jobs:
  test_sign:
    if: github.repository == 'MusculoskeletalAtlasProject/mapclient'
    name: create_release
    runs-on: windows-2019
    steps:
      - name: save secret to file
        run: | 
          base64 --help
          echo -n EV_CERTIFICATE_PFX_BASE64 > ev_certificate.pfx.base64
          base64 -d ev_certificate.pfx.base64 > ./ev_certificate.pfx
          ls

        env:
          EV_CERTIFICATE_PFX_BASE64: ${{ secrets.WIN_EV_CERTIFICATE_PFX_BASE64 }}
      - name: Sign application
        shell: bash
        run: |
          powershell -Command "(new-object net.webclient).DownloadString('https://github.com/MusculoskeletalAtlasProject/mapclient/releases/download/v0.20.1.rc2/MAP-Client-0.20.1.exe')"
          ls
          Signtool sign /?
      - name: Clean up
          shell: bash
          run: |
            rm ev_certificate.pfx.base64 ev_certificate.pfx
