name: test-win-signing

on:
  push

jobs:
  test_sign:
    if: github.repository == 'MusculoskeletalAtlasProject/mapclient'
    name: Test sign executable
    runs-on: windows-2019
    steps:
      - name: list stuff
        shell: cmd
        run: |
          echo "=========="
          dir "C:\Program Files (x86)\"
          echo "=========="
          dir "C:\Program Files (x86)\Windows Kits\"
          echo "=========="
          dir "C:\Program Files (x86)\Windows Kits\10\"
          echo "=========="
          dir "C:\Program Files (x86)\Windows Kits\10\bin\"
          echo "=========="
          dir "C:\Program Files (x86)\Windows Kits\10\bin\10.0.19041.0\"
          echo "=========="
          dir "C:\Program Files (x86)\Windows Kits\10\bin\10.0.19041.0\x86"
          echo "=========="
          dir "C:\Program Files (x86)\Windows Kits\10\bin\10.0.19041.0\x64"
          echo "=========="

      - name: save secret to file
        shell: bash
        run: | 
          echo -n $EV_CERTIFICATE_PFX_BASE64 | base64 -d - > ./ev_certificate.pfx
          ls -l

        env:
          EV_CERTIFICATE_PFX_BASE64: ${{ secrets.WIN_EV_CERTIFICATE_PFX_BASE64 }}
      - name: Get application
        shell: bash
        run: |
          powershell -Command "(new-object net.webclient).DownloadString('https://github.com/MusculoskeletalAtlasProject/mapclient/releases/download/v0.20.1.rc2/MAP-Client-0.20.1.exe')" > MAP-Client-0.20.1.exe
          ls -l

      - name: Sign application
        shell: cmd
        run: |
          "C:\Program Files (x86)\Windows Kits\10\bin\10.0.19041.0\x86\signtool" sign /d "MAP Client - mapping tools" /tr http://rfc3161timestamp.globalsign.com/advanced /td SHA256 /f ev_certificate.pfx MAP-Client-0.20.1.exe

      - name: Clean up
        shell: bash
        run: |
          rm ev_certificate.pfx
